//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.09 at 12:47:19 AM CEST 
//


package jps.hyperspin.module.database.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for headerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastlistupdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listversion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exporterversion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerType", propOrder = {
    "listname",
    "lastlistupdate",
    "listversion",
    "exporterversion"
})
public class HeaderType {

    protected String listname;
    protected String lastlistupdate;
    protected String listversion;
    protected String exporterversion;

    /**
     * Gets the value of the listname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListname() {
        return listname;
    }

    /**
     * Sets the value of the listname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListname(String value) {
        this.listname = value;
    }

    /**
     * Gets the value of the lastlistupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastlistupdate() {
        return lastlistupdate;
    }

    /**
     * Sets the value of the lastlistupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastlistupdate(String value) {
        this.lastlistupdate = value;
    }

    /**
     * Gets the value of the listversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListversion() {
        return listversion;
    }

    /**
     * Sets the value of the listversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListversion(String value) {
        this.listversion = value;
    }

    /**
     * Gets the value of the exporterversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterversion() {
        return exporterversion;
    }

    /**
     * Sets the value of the exporterversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterversion(String value) {
        this.exporterversion = value;
    }

}
